### ISSUE TITLE
Parametrized statements - Issue with quoted strings

### ISSUE THREAD

**Issue by calleay** [narendrans/sqlalchemy_dremio#14]
Hello,

We are currently experimenting with the parametrized statements support recently brought by b39604e48c3fe9269300d4bd14b96fe21b84e724 and faced an issue with the generated queries when the parameter's value contains single quotes.

As an example, the statement `SELECT * FROM cereal WHERE brand IN (?, ?)` having `Kellog's` and `Nestle` as values for the parameters will result in the following SQL statement, which syntax is invalid `SELECT * FROM cereal WHERE brand IN ('Kellog's', 'Nestle')`.

The observed behavior is likely due to the following code, which does not seem to properly escape string parameters :
https://github.com/narendrans/sqlalchemy_dremio/blob/1c4d19ec37595f1814e2f34bf3be6e47c5106965/sqlalchemy_dremio/base.py#L228-L239

Beyond the syntax issue with the generated queries, this implementation could also make the code vulnerable to SQL injection.

**Comment by chufe-dremio** [comment]
Done in 1.2.1, please let me know if it works.
Release available in PyPI.
