### ISSUE TITLE
Flight support for Passwords with = in them

### ISSUE THREAD

**Issue by c-thiel** [narendrans/sqlalchemy_dremio#18]
We are using Dremio with OAuth.
In order to access the API we then need to create an Access Token in Dremio. As these Dremio Tokens are base64 encoded by default, they always end with equal signs.

The Problem is now in: https://github.com/narendrans/sqlalchemy_dremio/blob/b87c878e240bdcb848568a8a71c49a7e1ed7c523/sqlalchemy_dremio/db.py#L53

Here, we split the password at the = sign and only send the item number 1. The problem is that the split does not only act on the first equal sign, but all of them.

A simple fix would be (I think):
```python
client.authenticate(HttpDremioClientAuthHandler(splits[0].split("=", 1)[1], splits[1].split("=", 1)[1])) 
```
thus limiting the number of splits to one and not splitting up the password at any occuring = further.

**Comment by jduo** [comment]
This is now fixed in #29.
