### ISSUE TITLE
Problem installing version 2.0.0 with pip

### ISSUE THREAD

**Issue by rmoretto** [narendrans/sqlalchemy_dremio#26]
Hello,

I'm trying to install the 2.0.0 version of the library via pip, which is giving me the following error:
```bash
$ pip install sqlalchemy-dremio==2.0.0
ERROR: Could not find a version that satisfies the requirement sqlalchemy-dremio==2.0.0 (from versions: 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1)
ERROR: No matching distribution found for sqlalchemy-dremio==2.0.0
```

It seems that pip can't find the latest version, running the same command but in verbose mode (`-vv`) I got the current log (truncated for readability):
```bash
$ pip install sqlalchemy-dremio==2.0.0 -vv
https://pypi.org:443 "GET /simple/sqlalchemy-dremio/ HTTP/1.1" 304 0
Fetched page https://pypi.org/simple/sqlalchemy-dremio/ as application/vnd.pypi.simple.v1+json
[...]
   Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/93/ef/bd72a44fe3a611f9f0992eb018fd6f40bcbbb689dc2501cbed312e950959/sqlalchemy_dremio-2.0.0-py3.9.egg (from https://pypi.org/simple/sqlalchemy-dremio/)
[...]
```

I'm no expert in python packaging, but it looks like that the 2.0.0 version of the lib was published as `.egg` format which pip does not support (as far I'm aware).

I tried installing the lib via git, I'm using the Superset tutorial for [adding new database drivers in docker](https://superset.apache.org/docs/databases/docker-add-drivers), but the Superset Docker image doesn't contains git installed by default, so I installed git in the Superset Docker image and successfully installed the `master` branch of the `sqlalchemy-dremio` in the Superset container, but when I got to create the new Dremio connection, the Dremio option doesn't seems to be available in the Superset `Connect Database` interface.

Am I doing something wrong? Is there something more that I can do to install the Dremio connector in the Superset image?

**Comment by narendrans** [comment]
Thanks for filing the issue. I just uploaded 2.0.2 which should work. Can you please try?


```(base) naren@lepton sqlalchemy_dremio % pip install sqlalchemy_dremio==2.0.2
Collecting sqlalchemy_dremio==2.0.2
  Using cached sqlalchemy_dremio-2.0.2-py2.py3-none-any.whl (17 kB)
Requirement already satisfied: pyarrow>=5.0.0 in /Users/naren/opt/anaconda3/lib/python3.9/site-packages (from sqlalchemy_dremio==2.0.2) (5.0.0)
Requirement already satisfied: sqlalchemy>=1.3.24 in /Users/naren/opt/anaconda3/lib/python3.9/site-packages (from sqlalchemy_dremio==2.0.2) (1.3.24)
Requirement already satisfied: numpy>=1.16.6 in /Users/naren/opt/anaconda3/lib/python3.9/site-packages (from pyarrow>=5.0.0->sqlalchemy_dremio==2.0.2) (1.22.1)
Installing collected packages: sqlalchemy_dremio
Successfully installed sqlalchemy_dremio-2.0.2```

**Comment by rmoretto** [comment]
It's working correctly now. Many thanks for the quick response!
