### ISSUE TITLE
Superset Dremio Connectivity

### ISSUE THREAD

**Issue by npc2kor** [narendrans/sqlalchemy_dremio#33]
Hi,

We have hosted Dremio and Superset on an AKS Cluster in Azure and we are trying to connect Superset to the Dremio Database(Lakehouse) for fetching some dashboards. We have installed all the required drivers(arrowflight, sqlalchemy_dremio and unixodc/dev) to establish the connection.

Strangely we are able not able to connect to Dremio from the Superset UI using the connection strings:

dremio+flight://admin:[password@dremiohostname.westeurope.cloudapp.azure.com](mailto:password@dremiohostname.westeurope.cloudapp.azure.com):32010/dremio
dremio://admin:[adminpass@dremiohostname.westeurope.cloudapp.azure.com](mailto:adminpass@dremiohostname.westeurope.cloudapp.azure.com):31010/databaseschema.dataset/dremio?SSL=0
Here's the error:

_(builtins.NoneType) None\n(Background on this error at: https://sqlalche.me/e/14/dbapi)", "error_type": "GENERIC_DB_ENGINE_ERROR", "level": "error", "extra": {"engine_name": "Dremio", "issue_codes": [{"code": 1002, "message": "Issue 1002 - The database returned an unexpected error."}]}}]_

However, while trying from inside the Superset pod, using this python script [here](https://github.com/dremio-hub/arrow-flight-client-examples/blob/main/python/example.py), the connection goes through without any issues.

**Comment by npc2kor** [comment]
@narendrans Could you share your thoughts here?

**Comment by jduo** [comment]
You should disable encryption if your server is unencrypted. It is on by default.:
dremio+flight://admin:password@dremiohostname.westeurope.cloudapp.azure.com/dremio?UseEncryption=false

**Comment by npc2kor** [comment]
It worked!!! Thanks a lot!!
